name: Python Package Publish and Streamlit Test

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies for building
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine pyngrok

      - name: Build Python package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --verbose dist/*

  test:
    name: Test Streamlit Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies for testing
        run: |
          python -m pip install --upgrade pip
          pip install pyngrok

      - name: Run Streamlit Application
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          python streamlit_colab/core.py app.py --port 8501
