name: Build, Publish, and Deploy

# Trigger the workflow on pushes to the main branch and when a new tag is created
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Example: v1.0.0

jobs:
  build:
    name: Build and Publish Package
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your Python version

      # Step 3: Install build dependencies
      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      # Step 4: Build the package
      - name: Build Package
        run: |
          python setup.py sdist bdist_wheel

      # Step 5: Upload to PyPI using Twine
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --verbose dist/*

  deploy:
    name: Deploy Streamlit App
    runs-on: ubuntu-latest
    needs: build  # This job depends on the 'build' job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your Python version

      # Step 3: Install application dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit pyngrok

      # Step 4: Run the Streamlit App with ngrok
      - name: Run Streamlit App with ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          nohup python streamlit_colab/core.py app.py --port 8501 &
          sleep 10  # Wait for the app and ngrok to initialize
          
          # Fetch and display the ngrok URL
          PUBLIC_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Streamlit app is accessible at: $PUBLIC_URL"
