name: Python Package Publish and Streamlit Test

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies for building the package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine pyngrok

      # Step 4: Build the package
      - name: Build Python package
        run: |
          python setup.py sdist bdist_wheel

      # Step 5: Publish the package to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --verbose dist/*

  test:
    name: Test Streamlit Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies for running the Streamlit app
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyngrok

      # Step 4: Run the Streamlit application with ngrok
      - name: Run Streamlit Application
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          python streamlit_colab/core.py app.py --port 8501
